name = "IntegerTriangles"
uuid = "715aea54-2823-4197-8122-618b5e027a3f"
authors = ["Peter Luschny"]
version = "0.2.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AbstractAlgebra = "0.15"
DocStringExtensions = "0.8"
Documenter = "0.26"
HTTP = "0.9"
Nemo = "0.22"
OrderedCollections = "1.4"
PrettyTables = "0.11"
julia = "1.6"
